name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    # instead of "ps2dev/ps2dev:latest" you can use different tags, for example for old projects you can use "ps2dev/ps2dev:v1.0"
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Compile project
      run: |
        git clone https://github.com/ps2homebrew/ps2Perf
        cd ps2Perf && make all && make install
        make all
    # commands for compiling your project
